### ISSUE TITLE
possible security issue in wp-readme

### ISSUE THREAD

**Issue by rtpHarry** [pyronaur/pyronaur.com#3]
Hello, I am seeing something strange which might be a security issue with wp-readme.com, but I cannot find any way to contact you privately.

**Comment by pyronaur** [comment]
you can use anything at pyronaur.com as email

**Comment by rtpHarry** [comment]
Hmm I tried to email ***@***.***, and then wondered if you were literal and tried ***@***.*** but they both get rejected.

From: **** ***** ***@***.***>
Date: Monday, 18 November 2024 at 15:46
To: pyronaur/pyronaur.com ***@***.***>
Cc: Matthew Harris ***@***.***>, Author ***@***.***>
Subject: Re: [pyronaur/pyronaur.com] possible security issue in wp-readme (Issue #3)


anything at my domain is an email you can use!

**Comment by pyronaur** [comment]
Huh, I mixed something up. Send it to `hi@pyronaur.com` that one at least I know exists, sorry for the goose chase 😅

**Comment by rtpHarry** [comment]
closing this as we have spoken privately about it
